version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/your_database_name
      SPRING_DATASOURCE_USERNAME: your_database_user
      SPRING_DATASOURCE_PASSWORD: your_database_password
    restart: always
    links:
      - "db:db"

  db:
    image: postgres:11
    ports:
      - "5433:5432"
    container_name: db
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

volumes:
  db-data:
    driver: local
